// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type ComponentInput struct {
	ID       string        `json:"id"`
	Type     ComponentType `json:"type"`
	Quantity int           `json:"quantity"`
}

type NewIngredient struct {
	Name         string `json:"name"`
	CurrentStock int    `json:"currentStock"`
	MinimumStock int    `json:"minimumStock"`
}

type NewRecipe struct {
	Name         string `json:"name"`
	CurrentStock int    `json:"currentStock"`
	MinimumStock int    `json:"minimumStock"`
}

type ComponentType string

const (
	ComponentTypeRecipe     ComponentType = "RECIPE"
	ComponentTypeIngredient ComponentType = "INGREDIENT"
)

var AllComponentType = []ComponentType{
	ComponentTypeRecipe,
	ComponentTypeIngredient,
}

func (e ComponentType) IsValid() bool {
	switch e {
	case ComponentTypeRecipe, ComponentTypeIngredient:
		return true
	}
	return false
}

func (e ComponentType) String() string {
	return string(e)
}

func (e *ComponentType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ComponentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ComponentType", str)
	}
	return nil
}

func (e ComponentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
